services:
  bchatdb:
    image: postgres:latest
    container_name: master_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=bchat
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - bchatdb
      - bchatredis
    environment:
      - ConnectionStrings__DefaultConnection=Server=bchatdb;Port=5432;Database=bchat;User Id=myuser;Password=mypassword;
      - Redis__ConnectionString=bchatredis:6379,abortConnect=false
    volumes:
      - .:/src
    command: dotnet BChatServer.dll --urls=http://+:8080
    
  bchatredis:
    image: redis:latest
    container_name: trans_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
volumes:
  pgdata:
  redis-data:
