services:
  db:
    image: postgres:latest
    container_name: master_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=dd
      - POSTGRES_DB=bchat
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=bchat;User Id=myuser;Password=mypassword;
      - Redis__ConnectionString=redis:6379,abortConnect=false
    volumes:
      - .:/src
    command: dotnet BChatServer.dll --urls=http://+:8080
    
  redis:
    image: redis:latest
    container_name: trans_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes


volumes:
  pgdata:
  redis-data:
